'use client';

import { useEffect, useMemo, useState } from 'react';
import Sidebar from '../components/Sidebar';
import AutomationCalendar, { RunHealthCards } from './AutomationCalendar';
import ProductPicker from './ProductPicker';
import PresetSummary from './PresetSummary';
import { applyPresetToAutomationForm, resolveAutomationAudience } from '@/lib/content-automation-audience';

const DEFAULT_PILLARS = ['Healthy Breakfast','Meal Prep System','Healthy Baking','Healthy Ingredients','Smart Kitchen','Healthy Snacks','Healthy Lifestyle Hacks'];
const EMPTY_FORM = {
  name:'Nutribake Weekly Planner',campaign_kind:'brand_editorial',brand_id:'',account_name:'nutribake',
  product_id:'',brand_product_id:'',product_name:'',product_description:'',product_usp:'',product_url:'',product_photo_url:'',
  affiliate_link:'',landing_page_url:'',tracking_code:'',cta_override:'',update_existing_binding:false,
  timezone:'Asia/Jakarta',frequency:'weekly',weekday:1,day_of_month:1,hour:8,minute:0,planner_count:7,
  pillars:DEFAULT_PILLARS.join('\n'),status:'paused',preset:'nutribake_editorial_v1',
  ai_directive:'Konten edukasi brand; jangan mengarang atau membahas produk tertentu.',mandatory_outro_line:'',
  target_audience:'Ibu rumah tangga dan keluarga muda usia 25–45 tahun.',content_goal:'Authority, engagement, saves, dan shares.',
  target_audience_source:'default',target_audience_manual:false,target_demographic:'ibu_rumah_tangga',target_demographic_custom:'',preset_summary:{},
  missed_run_policy:'skip',grace_minutes:60,max_catch_up_runs:3,max_attempts:3,base_seconds:60,max_seconds:900,
  auto_pause_threshold:5,approval_mode:'creative',auto_sync_contentflow:false
};
const EMPTY_NOTIFICATIONS={enabled:false,channel:'telegram',chat_id:'',bot_token:'',configured:false,events:['awaiting_approval','failed','auto_paused','missed_run'],quiet_start:'22:00',quiet_end:'07:00',timezone:'Asia/Jakarta'};
const NOTIFICATION_EVENTS=[['awaiting_approval','Menunggu approval'],['failed','Run gagal'],['auto_paused','Schedule auto-pause'],['missed_run','Missed run'],['completed','Run selesai']];
const overlay={position:'fixed',inset:0,background:'rgba(0,0,0,.72)',display:'flex',alignItems:'center',justifyContent:'center',zIndex:1000,padding:20};
const modal={width:'min(900px,96vw)',maxHeight:'92vh',overflowY:'auto',padding:24};
const grid=(min=220)=>({display:'grid',gridTemplateColumns:`repeat(auto-fit,minmax(${min}px,1fr))`,gap:12});

function parseJson(value,fallback={}){try{return typeof value==='string'?JSON.parse(value):value||fallback;}catch{return fallback;}}
function stageLabel(status){return ({generating_creative:'Creative',generating_start_frames:'Start Frames',awaiting_approval:'Approval',partially_approved:'Partial Approval',producing:'Production',syncing_contentflow:'ContentFlow',completed_with_warnings:'Completed with warnings'})[status]||status;}

export default function ContentAutomationsPage(){
  const [data,setData]=useState({schedules:[],runs:[],notifications:[]});
  const [brands,setBrands]=useState([]),[products,setProducts]=useState([]),[presets,setPresets]=useState([]),[user,setUser]=useState(null);
  const [flags,setFlags]=useState({enabled:false,pilotEnabled:false});
  const [productSearch,setProductSearch]=useState(''),[productState,setProductState]=useState({loading:false,error:'',summary:null});
  const [busy,setBusy]=useState(false),[message,setMessage]=useState(''),[showSchedule,setShowSchedule]=useState(false),[showNotifications,setShowNotifications]=useState(false);
  const [form,setForm]=useState(EMPTY_FORM),[notificationForm,setNotificationForm]=useState(EMPTY_NOTIFICATIONS);
  const [view,setView]=useState('list'),[calendarMode,setCalendarMode]=useState('month'),[calendarAnchor,setCalendarAnchor]=useState(()=>new Date().toISOString().slice(0,10));
  const [calendar,setCalendar]=useState({events:[],health:{}}),[calendarFilters,setCalendarFilters]=useState({schedule_id:'',brand_id:'',status:'',timezone:'Asia/Jakarta'});
  const selectedProduct=useMemo(()=>products.find(product=>product.product_id===form.product_id)||null,[products,form.product_id]);
  const selectedPreset=useMemo(()=>presets.find(preset=>preset.key===form.preset)||null,[presets,form.preset]);
  const compatiblePresets=useMemo(()=>presets.filter(preset=>(preset.config?.campaign_kinds||['brand_editorial']).includes(form.campaign_kind)),[presets,form.campaign_kind]);

  async function load(){
    const [a,b,c,u,f]=await Promise.all([fetch('/api/v2/content-automations').then(r=>r.json()),fetch('/api/v2/brand-profiles').then(r=>r.json()),fetch('/api/v2/operator-presets').then(r=>r.json()),fetch('/api/auth/me').then(r=>r.json()),fetch('/api/v2/content-automations/feature-flags').then(r=>r.json())]);
    if(a.success)setData(a);if(b.success)setBrands(b.data||[]);if(c.success)setPresets(c.presets||[]);if(u.authenticated)setUser(u.user);if(f.success)setFlags(f.flags);
  }
  useEffect(()=>{load();},[]);
  async function loadProducts(){if(!form.brand_id||form.campaign_kind!=='product_campaign'){setProducts([]);setProductState({loading:false,error:'',summary:null});return;}setProductState(state=>({...state,loading:true,error:''}));const query=new URLSearchParams({brand_profile_id:form.brand_id});if(productSearch.trim())query.set('search',productSearch.trim());try{const response=await fetch(`/api/v2/content-automations/product-options?${query}`),result=await response.json();if(!result.success)throw new Error(result.error);setProducts(result.products||[]);setProductState({loading:false,error:'',summary:result.summary||null});}catch(error){setProducts([]);setProductState({loading:false,error:error.message,summary:null});}}
  useEffect(()=>{const timer=setTimeout(loadProducts,250);return()=>clearTimeout(timer);},[form.brand_id,form.campaign_kind,productSearch]);
  useEffect(()=>{if(view!=='calendar')return;const anchor=new Date(`${calendarAnchor}T12:00:00Z`),from=new Date(anchor);if(calendarMode==='week')from.setUTCDate(from.getUTCDate()-from.getUTCDay());else{from.setUTCDate(1);from.setUTCDate(from.getUTCDate()-from.getUTCDay());}const to=new Date(from.getTime()+(calendarMode==='week'?7:42)*86400000);const q=new URLSearchParams({from:from.toISOString(),to:to.toISOString(),timezone:calendarFilters.timezone});for(const [key,value] of Object.entries(calendarFilters))if(value&&key!=='timezone')q.set(key,value);fetch(`/api/v2/content-automations/calendar?${q}`).then(r=>r.json()).then(j=>j.success?setCalendar(j):setMessage(j.error));},[view,calendarMode,calendarAnchor,calendarFilters]);

  function setCampaignKind(kind){const presetKey=kind==='product_campaign'?'product_campaign_v1':'nutribake_editorial_v1',preset=presets.find(item=>item.key===presetKey);let next={...EMPTY_FORM,campaign_kind:kind,name:kind==='product_campaign'?'Product Campaign Weekly':'Nutribake Weekly Planner',planner_count:kind==='product_campaign'?6:7,preset:presetKey,approval_mode:kind==='product_campaign'?'start_frames':'creative',auto_sync_contentflow:kind==='product_campaign',target_audience:kind==='product_campaign'?'':'Ibu rumah tangga dan keluarga muda usia 25–45 tahun.',target_audience_source:kind==='product_campaign'?'auto':'default',target_demographic:kind==='product_campaign'?'custom':'ibu_rumah_tangga',ai_directive:kind==='product_campaign'?'Gunakan hanya klaim, USP, dan fakta pada snapshot produk.':'Konten edukasi brand; jangan mengarang atau membahas produk tertentu.'};if(preset)next=applyPresetToAutomationForm(next,preset);setProductSearch('');setForm(next);}
  function selectBrand(id){const brand=brands.find(item=>item.id===id);setForm({...form,brand_id:id,account_name:brand?.brand_name||'',product_id:'',brand_product_id:''});}
  function selectProduct(id){const product=products.find(item=>item.product_id===id);const audience=resolveAutomationAudience({manualValue:form.target_audience,manualLocked:form.target_audience_manual,productAudience:product?.target_audience,presetAudience:selectedPreset?.config?.planner_defaults?.target_audience});setForm({...form,product_id:id,brand_product_id:product?.brand_product_id||'',product_name:product?.product_name||'',product_description:product?.product_description||'',product_usp:product?.unique_selling_point||'',product_url:product?.landing_page_url||product?.source_url||'',product_photo_url:product?.image_url||'',affiliate_link:product?.affiliate_link||'',landing_page_url:product?.landing_page_url||'',tracking_code:product?.tracking_code||'',cta_override:product?.cta_override||'',update_existing_binding:false,target_audience:audience.value,target_audience_source:audience.source});}
  function payload(){
    const pillars=form.pillars.split('\n').map(value=>value.trim()).filter(Boolean);
    const planner=form.campaign_kind==='product_campaign'?{planner_focus:'product_campaign',title:`${form.product_name} Scheduled Product Campaign`,brand_id:form.brand_id,account_name:form.account_name,product_id:form.product_id,brand_product_id:form.brand_product_id,product_name:form.product_name,product_description:form.product_description,product_usp:form.product_usp,product_url:form.product_url,product_photo_url:form.product_photo_url,target_audience:form.target_audience,content_goal:form.content_goal,planner_count:Number(form.planner_count),platform:'tiktok'}:{planner_focus:'brand_editorial',title:`${form.account_name} Scheduled Editorial`,account_name:form.account_name,brand_id:form.brand_id||undefined,brand_context:form.ai_directive,content_goal:form.content_goal,target_audience:form.target_audience,pillars,planner_count:Number(form.planner_count),platform:'tiktok'};
    return {name:form.name,campaign_kind:form.campaign_kind,status:form.status,timezone:form.timezone,frequency:form.frequency,schedule:{weekday:Number(form.weekday),hour:Number(form.hour),minute:Number(form.minute),day_of_month:Number(form.day_of_month)},missed_run_policy:form.missed_run_policy,grace_minutes:Number(form.grace_minutes),max_catch_up_runs:Number(form.max_catch_up_runs),retry_policy:{max_attempts:Number(form.max_attempts),base_seconds:Number(form.base_seconds),max_seconds:Number(form.max_seconds)},auto_pause_threshold:Number(form.auto_pause_threshold),product_binding:form.campaign_kind==='product_campaign'?{product_id:form.product_id,affiliate_link:form.affiliate_link,landing_page_url:form.landing_page_url,tracking_code:form.tracking_code,cta_override:form.cta_override,update_existing:form.update_existing_binding}:undefined,operator_request:{planner,selection:{mode:'all'},opc:{preset:form.preset,basic_strategy:{brand_profile_id:form.brand_id||undefined,account_name:form.account_name,product_id:form.product_id||undefined,target_product_id:form.product_id||undefined,campaign_name:`[Scheduled OPC] ${form.name}`,ai_directive:form.ai_directive,mandatory_outro_line:form.mandatory_outro_line,target_demographic:form.target_demographic,target_demographic_custom:form.target_demographic_custom},workflow:{approval_mode:form.approval_mode,auto_sync_contentflow:form.auto_sync_contentflow,enable_social_post:false}}}};
  }
  async function create(event){event.preventDefault();setBusy(true);const response=await fetch('/api/v2/content-automations',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(payload())}),result=await response.json();setBusy(false);setMessage(result.success?'Schedule tersimpan dalam mode paused.':result.error);if(result.success){setShowSchedule(false);setForm(EMPTY_FORM);load();}}
  async function scheduleAction(id,type,status){setBusy(true);const response=type==='run'?await fetch(`/api/v2/content-automations/${id}/run-now`,{method:'POST'}):await fetch(`/api/v2/content-automations/${id}`,{method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify({status})}),result=await response.json();setBusy(false);setMessage(result.success?(type==='run'?`Run dibuat: ${result.run_id}`:`Schedule ${status}.`):result.error);load();}
  async function retry(id){setBusy(true);const result=await fetch(`/api/v2/content-automations/runs/${id}/retry`,{method:'POST'}).then(r=>r.json());setBusy(false);setMessage(result.success?`Retry attempt ${result.attempt_count} dibuat.`:result.error);load();}
  async function retryContentFlow(id){setBusy(true);const result=await fetch(`/api/v2/content-automations/runs/${id}/retry-contentflow`,{method:'POST'}).then(r=>r.json());setBusy(false);setMessage(result.success?`${result.synced.length} item berhasil disinkronkan.`:(result.error||`${result.failed?.length||0} sync gagal.`));load();}
  async function approve(run){setBusy(true);const response=await fetch(`/api/v2/content-automations/runs/${run.id}/review`).then(r=>r.json());if(!response.success){setBusy(false);return setMessage(response.error);}const review=response.review;const ready=(review.item_summaries||[]).filter(item=>item.workflow_status==='ready_for_review');const ok=window.confirm(`Approve ${ready.length} item yang siap?\n\n${review.start_frame_count||0} start frame · ${review.clip_count} klip\nRevision: ${review.revision}\n\nTTS, video, dan FFmpeg akan dimulai.`);if(!ok){setBusy(false);return;}const result=await fetch(`/api/v2/content-automations/runs/${run.id}/approve`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({mode:'approve_ready',item_ids:ready.map(item=>item.id),review_revision:review.revision,review_sha256:review.sha256})}).then(r=>r.json());setBusy(false);setMessage(result.success?`${result.approved_count} item disetujui untuk produksi.`:result.error);load();}
  function choosePreset(key){const preset=presets.find(item=>item.key===key);if(!preset)return;let next=applyPresetToAutomationForm(form,preset);if(!form.target_audience_manual){const audience=resolveAutomationAudience({productAudience:selectedProduct?.target_audience,presetAudience:preset.config?.planner_defaults?.target_audience});next={...next,target_audience:audience.value,target_audience_source:audience.source};}setForm(next);}
  async function archiveSchedule(schedule){if(!window.confirm(`Archive schedule ${schedule.name}?`))return;setBusy(true);const result=await fetch(`/api/v2/content-automations/${schedule.id}`,{method:'DELETE'}).then(r=>r.json());setBusy(false);setMessage(result.success?'Schedule diarsipkan.':result.error);load();}
  async function deleteRun(run){if(!window.confirm(`Hapus run ${run.id} dari automation history?`))return;setBusy(true);const result=await fetch(`/api/v2/content-automations/runs/${run.id}`,{method:'DELETE'}).then(r=>r.json());setBusy(false);setMessage(result.success?'Run history dihapus.':result.error);load();}
  async function openNotifications(){setBusy(true);const result=await fetch('/api/v2/content-automations/notification-settings').then(r=>r.json());setBusy(false);if(!result.success)return setMessage(result.error);setNotificationForm({...EMPTY_NOTIFICATIONS,...result.settings,bot_token:''});setShowNotifications(true);}
  async function saveNotifications(event){event.preventDefault();setBusy(true);const result=await fetch('/api/v2/content-automations/notification-settings',{method:'PUT',headers:{'Content-Type':'application/json'},body:JSON.stringify(notificationForm)}).then(r=>r.json());setBusy(false);setMessage(result.success?'Pengaturan notifikasi tersimpan.':result.error);}
  async function updateFlags(next){setBusy(true);const result=await fetch('/api/v2/content-automations/feature-flags',{method:'PUT',headers:{'Content-Type':'application/json'},body:JSON.stringify(next)}).then(r=>r.json());setBusy(false);if(result.success)setFlags(result.flags);setMessage(result.success?'Feature flag Product Campaign diperbarui.':result.error);}
  function toggleNotificationEvent(key){setNotificationForm({...notificationForm,events:notificationForm.events.includes(key)?notificationForm.events.filter(item=>item!==key):[...notificationForm.events,key]});}

  return <><Sidebar/><main className="main-content" style={{padding:32}}>
    <div className="page-header" style={{display:'flex',justifyContent:'space-between',alignItems:'center',gap:16}}><div><h1>⏱️ Content Automations</h1><p className="page-subtitle">Brand Editorial dan Product Campaign berbasis OPC — review setelah creative atau seluruh start frame siap.</p></div><div style={{display:'flex',gap:8}}>{user?.role==='admin'&&<button className="btn btn-secondary" onClick={openNotifications}>Notification Settings</button>}<button className="btn btn-primary" onClick={()=>setShowSchedule(true)}>+ New Schedule</button></div></div>
    {user?.role==='admin'&&<div className="card" style={{padding:12,marginBottom:16,display:'flex',gap:18,flexWrap:'wrap'}}><b>Product Campaign</b><label><input type="checkbox" checked={flags.enabled} disabled={busy} onChange={event=>updateFlags({enabled:event.target.checked})}/> Tersedia untuk pembuatan schedule</label><label><input type="checkbox" checked={flags.pilotEnabled} disabled={busy||!flags.enabled} onChange={event=>updateFlags({pilotEnabled:event.target.checked})}/> Izinkan eksekusi pilot</label></div>}
    {message&&<div className="card" style={{padding:12,marginBottom:16}}>{message}</div>}
    <div style={{display:'grid',gap:18,maxWidth:1250}}>
      {data.notifications?.some(item=>!item.read_at)&&<div className="card" style={{padding:16,borderColor:'var(--warning)'}}>🔔 <b>{data.notifications.filter(item=>!item.read_at).length} campaign menunggu perhatian</b></div>}
      <RunHealthCards health={calendar.health}/>
      <div style={{display:'flex',gap:8}}><button className={`btn ${view==='list'?'btn-primary':'btn-secondary'}`} onClick={()=>setView('list')}>List</button><button className={`btn ${view==='calendar'?'btn-primary':'btn-secondary'}`} onClick={()=>setView('calendar')}>Calendar</button></div>
      {view==='calendar'?<section className="card" style={{padding:20}}><div style={{display:'flex',justifyContent:'space-between',marginBottom:12}}><h3>Automation Calendar</h3><div style={{display:'flex',gap:6}}><button className="btn btn-secondary btn-sm" onClick={()=>{const d=new Date(`${calendarAnchor}T12:00:00Z`);calendarMode==='week'?d.setUTCDate(d.getUTCDate()-7):d.setUTCMonth(d.getUTCMonth()-1);setCalendarAnchor(d.toISOString().slice(0,10));}}>←</button><select className="form-select" value={calendarMode} onChange={e=>setCalendarMode(e.target.value)}><option value="month">Month</option><option value="week">Week</option></select><button className="btn btn-secondary btn-sm" onClick={()=>{const d=new Date(`${calendarAnchor}T12:00:00Z`);calendarMode==='week'?d.setUTCDate(d.getUTCDate()+7):d.setUTCMonth(d.getUTCMonth()+1);setCalendarAnchor(d.toISOString().slice(0,10));}}>→</button></div></div><AutomationCalendar events={calendar.events} timezone={calendarFilters.timezone} mode={calendarMode} anchor={calendarAnchor}/></section>:<section className="card" style={{padding:20}}><h3>Schedules</h3>{data.schedules.length===0?<p>Belum ada schedule.</p>:data.schedules.map(schedule=><div key={schedule.id} style={{padding:'14px 0',borderBottom:'1px solid var(--border-color)',display:'flex',justifyContent:'space-between',gap:12,flexWrap:'wrap'}}><div><b>{schedule.name}</b> <span style={{fontSize:11,color:schedule.campaign_kind==='product_campaign'?'var(--accent-color)':'var(--text-muted)'}}>· {schedule.campaign_kind==='product_campaign'?'Product Campaign':'Brand Editorial'}</span><div style={{fontSize:12,color:'var(--text-muted)'}}>{schedule.frequency} · {schedule.timezone} · next {schedule.next_run_at?new Date(schedule.next_run_at).toLocaleString('id-ID'):'-'}</div></div><div style={{display:'flex',gap:7}}><button disabled={busy} className="btn btn-secondary btn-sm" onClick={()=>scheduleAction(schedule.id,'run')}>Run Now</button><button disabled={busy} className={`btn btn-sm ${schedule.status==='active'?'btn-danger':'btn-success'}`} onClick={()=>scheduleAction(schedule.id,'toggle',schedule.status==='active'?'paused':'active')}>{schedule.status==='active'?'Pause':'Aktifkan'}</button>{user?.role==='admin'&&<button disabled={busy} className="btn btn-secondary btn-sm" onClick={()=>archiveSchedule(schedule)}>Archive</button>}</div></div>)}</section>}
      <section className="card" style={{padding:20}}><h3>Run History</h3>{data.runs.length===0?<p>Belum ada run.</p>:data.runs.slice(0,30).map(run=>{const snapshot=parseJson(run.product_snapshot_json,null);const total=Number(run.total_item_count||0),approved=Number(run.approved_item_count||0),synced=Number(run.contentflow_synced_count||0);return <div key={run.id} style={{padding:'14px 0',borderBottom:'1px solid var(--border-color)',display:'grid',gridTemplateColumns:'minmax(260px,1fr) minmax(260px,1fr) auto',gap:14,alignItems:'center'}}><div><b>{run.schedule_name}</b><div style={{fontSize:12,color:'var(--text-muted)'}}>{snapshot?.product_name||run.campaign_kind?.replace('_',' ')} · {stageLabel(run.status)}</div><div style={{fontSize:11,color:'var(--text-muted)'}}>{run.id} · attempt {run.attempt_count}</div></div><div style={{fontSize:11}}><div>Approval {approved}/{total||'-'} · ContentFlow {synced}/{approved||'-'}</div><div style={{height:6,background:'var(--border-color)',borderRadius:6,marginTop:6}}><div style={{height:'100%',width:`${total?Math.round(approved/total*100):0}%`,background:'var(--accent-color)',borderRadius:6}}/></div></div><div style={{display:'flex',gap:6,flexWrap:'wrap',justifyContent:'flex-end'}}>{run.operator_campaign_id&&<a className="btn btn-secondary btn-sm" href={`/pillar-campaigns/${run.operator_campaign_id}`}>Open OPC Review</a>}{['awaiting_approval','partially_approved'].includes(run.status)&&user?.role==='admin'&&<button disabled={busy} className="btn btn-primary btn-sm" onClick={()=>approve(run)}>Approve All Ready Items</button>}{['syncing_contentflow','completed_with_warnings'].includes(run.status)&&<button className="btn btn-secondary btn-sm" onClick={()=>retryContentFlow(run.id)}>Retry ContentFlow</button>}{run.status==='failed'&&<button className="btn btn-secondary btn-sm" onClick={()=>retry(run.id)}>Retry</button>}{user?.role==='admin'&&['completed','completed_with_warnings','failed','skipped','awaiting_approval'].includes(run.status)&&<button className="btn btn-danger btn-sm" onClick={()=>deleteRun(run)}>Delete</button>}</div></div>})}</section>
    </div>

    {showSchedule&&<div style={overlay}><form className="card" style={modal} onSubmit={create}><div style={{display:'flex',justifyContent:'space-between'}}><div><h2>New Content Automation</h2><p className="page-subtitle">Product Campaign selalu memakai pipeline OPC.</p></div><button type="button" className="btn btn-secondary btn-sm" onClick={()=>setShowSchedule(false)}>Close</button></div><div style={{display:'grid',gap:14}}>
      <fieldset style={{border:'1px solid var(--border-color)',borderRadius:10,padding:14}}><legend>Campaign Type</legend><div style={grid()}><button type="button" className={`btn ${form.campaign_kind==='brand_editorial'?'btn-primary':'btn-secondary'}`} onClick={()=>setCampaignKind('brand_editorial')}>◇ Brand Editorial</button><button type="button" disabled={!flags.enabled} title={!flags.enabled?'Dinonaktifkan oleh Admin tenant':''} className={`btn ${form.campaign_kind==='product_campaign'?'btn-primary':'btn-secondary'}`} onClick={()=>setCampaignKind('product_campaign')}>□ Product Campaign</button></div>{!flags.enabled&&<small>Product Campaign sedang dinonaktifkan oleh Admin tenant.</small>}</fieldset>
      <label>Nama Schedule<input required className="form-input" value={form.name} onChange={e=>setForm({...form,name:e.target.value})}/></label>
      <div style={grid()}><label>Brand Profile<select required={form.campaign_kind==='product_campaign'} className="form-select" value={form.brand_id} onChange={e=>selectBrand(e.target.value)}><option value="">Pilih Brand Profile</option>{brands.map(brand=><option key={brand.id} value={brand.id}>{brand.brand_name}</option>)}</select></label>{form.campaign_kind==='product_campaign'&&<label>Produk dari Data Produk<ProductPicker products={products} value={form.product_id} loading={productState.loading} error={productState.error} summary={productState.summary} search={productSearch} onSearch={setProductSearch} onChange={selectProduct} onRetry={loadProducts}/></label>}</div>
      {form.campaign_kind==='product_campaign'&&selectedProduct&&<><div style={{padding:14,border:`1px solid ${selectedProduct.is_linked?'var(--status-success)':'var(--warning)'}`,borderRadius:10,display:'flex',gap:14}}>{selectedProduct.image_url&&<img src={selectedProduct.image_url} alt="" style={{width:72,height:72,objectFit:'contain',borderRadius:8}}/>}<div><b>{selectedProduct.product_name}</b> · <span>{selectedProduct.is_linked?'Linked':'Not linked — binding dibuat saat Save'}</span><div style={{fontSize:12,color:'var(--text-muted)',marginTop:5}}>{selectedProduct.product_description||'Deskripsi belum tersedia'}</div><div style={{fontSize:11,marginTop:7}}>{Object.entries(selectedProduct.completeness||{}).map(([key,value])=>`${value?'✓':'✕'} ${key}`).join(' · ')}</div></div></div><fieldset style={{border:'1px solid var(--border-color)',borderRadius:10,padding:12}}><legend>Affiliate Routing</legend><div style={grid()}><label>Affiliate Link<input className="form-input" value={form.affiliate_link} onChange={e=>setForm({...form,affiliate_link:e.target.value})}/></label><label>Landing Page<input className="form-input" value={form.landing_page_url} onChange={e=>setForm({...form,landing_page_url:e.target.value})}/></label><label>Tracking Code<input className="form-input" value={form.tracking_code} onChange={e=>setForm({...form,tracking_code:e.target.value})}/></label><label>CTA Override<input className="form-input" value={form.cta_override} onChange={e=>setForm({...form,cta_override:e.target.value})}/></label></div>{selectedProduct.is_linked&&<label style={{display:'flex',gap:8,marginTop:8}}><input type="checkbox" checked={form.update_existing_binding} onChange={e=>setForm({...form,update_existing_binding:e.target.checked})}/> Perbarui routing existing dengan nilai di atas</label>}</fieldset></>}
      <div style={grid()}><label>OPC Preset<select className="form-select" value={form.preset} onChange={e=>choosePreset(e.target.value)}>{compatiblePresets.map(preset=><option key={preset.key} value={preset.key}>{preset.label}</option>)}</select></label><label>Planner Count<select className="form-select" value={form.planner_count} onChange={e=>setForm({...form,planner_count:e.target.value})}>{form.campaign_kind==='product_campaign'?[6,12,18,24,30].map(value=><option key={value}>{value}</option>):<>{Array.from({length:Math.floor(30/Math.max(1,form.pillars.split('\n').filter(Boolean).length))},(_,index)=>(index+1)*form.pillars.split('\n').filter(Boolean).length).map(value=><option key={value}>{value}</option>)}</>}</select></label><label>Approval Mode<select className="form-select" value={form.approval_mode} onChange={e=>setForm({...form,approval_mode:e.target.value})}>{form.campaign_kind==='product_campaign'&&<option value="start_frames">Review after Start Frames</option>}<option value="creative">Review Creative</option><option value="none">Full Auto</option></select></label></div>
      <PresetSummary preset={selectedPreset} summary={form.preset_summary} onReset={()=>choosePreset(form.preset)}/>
      {form.campaign_kind==='brand_editorial'&&<label>Pilar, satu per baris<textarea className="form-input" rows={6} value={form.pillars} onChange={e=>setForm({...form,pillars:e.target.value})}/></label>}
      <div style={grid()}><label>Target Audience <small>Source: {form.target_audience_source}</small><input required className="form-input" value={form.target_audience} onChange={e=>setForm({...form,target_audience:e.target.value,target_audience_manual:true,target_audience_source:'manual'})}/>{form.campaign_kind==='product_campaign'&&form.target_audience_manual&&<button type="button" className="btn btn-secondary btn-sm" onClick={()=>{const audience=resolveAutomationAudience({productAudience:selectedProduct?.target_audience,presetAudience:selectedPreset?.config?.planner_defaults?.target_audience});setForm({...form,target_audience:audience.value,target_audience_source:audience.source,target_audience_manual:false});}}>Reset ke Auto</button>}</label><label>Content Goal<input className="form-input" value={form.content_goal} onChange={e=>setForm({...form,content_goal:e.target.value})}/></label></div>
      {form.campaign_kind==='product_campaign'&&<div style={grid()}><label>Visual Subject<select className="form-select" value={form.target_demographic} onChange={e=>setForm({...form,target_demographic:e.target.value})}>{['genz_casual','ibu_rumah_tangga','professional_executive','hijab_syari_family','fitness_health_enthusiast','custom'].map(value=><option key={value}>{value}</option>)}</select></label>{form.target_demographic==='custom'&&<label>Visual Subject Custom<input required className="form-input" value={form.target_demographic_custom} onChange={e=>setForm({...form,target_demographic_custom:e.target.value})} placeholder="Contoh: Perempuan Indonesia usia 25–40"/></label>}</div>}
      <label>AI Directive / Guardrail<textarea className="form-input" rows={3} value={form.ai_directive} onChange={e=>setForm({...form,ai_directive:e.target.value})}/><small>Tidak diucapkan dalam voice-over.</small></label>
      <label>Mandatory Outro Line<textarea className="form-input" rows={2} value={form.mandatory_outro_line} onChange={e=>setForm({...form,mandatory_outro_line:e.target.value})}/></label>
      {form.campaign_kind==='product_campaign'&&<label style={{display:'flex',gap:8,alignItems:'center'}}><input type="checkbox" checked={form.auto_sync_contentflow} onChange={e=>setForm({...form,auto_sync_contentflow:e.target.checked})}/> Automatic ContentFlow Sync setelah FFmpeg</label>}
      <div style={grid(150)}><label>Frekuensi<select className="form-select" value={form.frequency} onChange={e=>setForm({...form,frequency:e.target.value})}><option value="daily">Harian</option><option value="weekly">Mingguan</option><option value="monthly">Bulanan</option></select></label>{form.frequency==='weekly'&&<label>Hari<select className="form-select" value={form.weekday} onChange={e=>setForm({...form,weekday:e.target.value})}>{['Minggu','Senin','Selasa','Rabu','Kamis','Jumat','Sabtu'].map((label,index)=><option key={label} value={index}>{label}</option>)}</select></label>}<label>Jam<input className="form-input" type="number" min="0" max="23" value={form.hour} onChange={e=>setForm({...form,hour:e.target.value})}/></label><label>Menit<input className="form-input" type="number" min="0" max="59" value={form.minute} onChange={e=>setForm({...form,minute:e.target.value})}/></label><label>Timezone<input className="form-input" value={form.timezone} onChange={e=>setForm({...form,timezone:e.target.value})}/></label></div>
      <div style={{padding:12,border:'1px solid var(--border-color)',borderRadius:8,fontSize:12}}>Pipeline: Planner → OPC creative → {form.approval_mode==='start_frames'?'Start Frames → Review':'Review'} → TTS → Video → FFmpeg → {form.auto_sync_contentflow?'ContentFlow':'Selesai'} · Social posting off.</div>
      <div style={{display:'flex',justifyContent:'flex-end',gap:8}}><button type="button" className="btn btn-secondary" onClick={()=>setShowSchedule(false)}>Cancel</button><button disabled={busy||form.campaign_kind==='product_campaign'&&(!selectedProduct||!form.target_audience.trim()||form.target_demographic==='custom'&&!form.target_demographic_custom.trim()||!selectedProduct.completeness?.description)} className="btn btn-primary">Save Schedule</button></div>
    </div></form></div>}

    {showNotifications&&<div style={overlay}><form className="card" style={modal} onSubmit={saveNotifications}><div style={{display:'flex',justifyContent:'space-between'}}><h2>Telegram Notifications</h2><button type="button" className="btn btn-secondary btn-sm" onClick={()=>setShowNotifications(false)}>Close</button></div><div style={{display:'grid',gap:12}}><label style={{display:'flex',gap:8}}><input type="checkbox" checked={notificationForm.enabled} onChange={e=>setNotificationForm({...notificationForm,enabled:e.target.checked})}/> Aktifkan notifikasi</label><label>Chat ID<input className="form-input" value={notificationForm.chat_id} onChange={e=>setNotificationForm({...notificationForm,chat_id:e.target.value})}/></label><label>Bot Token<input className="form-input" type="password" value={notificationForm.bot_token} onChange={e=>setNotificationForm({...notificationForm,bot_token:e.target.value})}/></label>{NOTIFICATION_EVENTS.map(([key,label])=><label key={key} style={{display:'flex',gap:8}}><input type="checkbox" checked={notificationForm.events.includes(key)} onChange={()=>toggleNotificationEvent(key)}/>{label}</label>)}<button disabled={busy} className="btn btn-primary">Save Settings</button></div></form></div>}
  </main></>;
}
