'use client';
import { useEffect,useState } from 'react';

const DEFAULT_PILLARS=['Healthy Breakfast','Meal Prep System','Healthy Baking','Healthy Ingredients','Smart Kitchen','Healthy Snacks','Healthy Lifestyle Hacks'];
export default function ContentAutomationsPage(){const [data,setData]=useState({schedules:[],runs:[],notifications:[]}),[brands,setBrands]=useState([]),[busy,setBusy]=useState(false),[message,setMessage]=useState('');
const [form,setForm]=useState({name:'Nutribake Weekly Planner',brand_id:'',account_name:'nutribake',timezone:'Asia/Jakarta',frequency:'weekly',weekday:1,day_of_month:1,hour:8,minute:0,planner_count:7,pillars:DEFAULT_PILLARS.join('\n'),status:'paused'});
async function load(){const [a,b]=await Promise.all([fetch('/api/v2/content-automations').then(r=>r.json()),fetch('/api/v2/brand-profiles').then(r=>r.json())]);if(a.success)setData(a);if(b.success)setBrands(b.data||[]);}
useEffect(()=>{load();},[]);
function request(){const pillars=form.pillars.split('\n').map(v=>v.trim()).filter(Boolean);return {name:form.name,status:form.status,timezone:form.timezone,frequency:form.frequency,schedule:{weekday:Number(form.weekday),hour:Number(form.hour),minute:Number(form.minute),day_of_month:Number(form.day_of_month)},operator_request:{planner:{planner_focus:'brand_editorial',title:`${form.account_name} Scheduled Editorial`,account_name:form.account_name,brand_id:form.brand_id||undefined,brand_context:'Konten edukasi brand; jangan mengarang atau membahas produk tertentu.',content_goal:'Authority, engagement, saves, dan shares.',target_audience:'Ibu rumah tangga dan keluarga muda usia 25–45 tahun.',pillars,planner_count:Number(form.planner_count),platform:'tiktok'},selection:{mode:'all'},opc:{preset:'nutribake_editorial_v1',basic_strategy:{brand_profile_id:form.brand_id||undefined,account_name:form.account_name,campaign_name:`[Scheduled OPC] ${form.name}`},workflow:{approval_mode:'storyboard',enable_social_post:false}}}};}
async function create(e){e.preventDefault();setBusy(true);setMessage('');const r=await fetch('/api/v2/content-automations',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(request())});const j=await r.json();setMessage(j.success?'Schedule tersimpan dalam mode '+form.status:j.error);setBusy(false);if(j.success)load();}
async function action(id,type,status){setBusy(true);let r;if(type==='run')r=await fetch(`/api/v2/content-automations/${id}/run-now`,{method:'POST'});else r=await fetch(`/api/v2/content-automations/${id}`,{method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify({status})});const j=await r.json();setMessage(j.success?(type==='run'?`Run dibuat: ${j.run_id}`:`Schedule ${status}`):j.error);setBusy(false);load();}
async function retry(runId){setBusy(true);const r=await fetch(`/api/v2/content-automations/runs/${runId}/retry`,{method:'POST'}),j=await r.json();setMessage(j.success?`Retry attempt ${j.attempt_count} dibuat.`:j.error);setBusy(false);load();}
return <main className="main-content"><div className="page-header"><div><h1>⏱️ Content Automations</h1><p className="page-subtitle">Scheduler native MAKNA — berhenti di storyboard sampai approval.</p></div></div>
<div style={{display:'grid',gridTemplateColumns:'minmax(330px,1fr) minmax(430px,1.4fr)',gap:20}}><form onSubmit={create} className="card" style={{padding:20,display:'grid',gap:12}}><h3>Schedule Baru</h3>
<label>Nama<input className="form-input" value={form.name} onChange={e=>setForm({...form,name:e.target.value})}/></label>
<label>Brand Profile<select className="form-select" value={form.brand_id} onChange={e=>{const b=brands.find(x=>x.id===e.target.value);setForm({...form,brand_id:e.target.value,account_name:b?.brand_name||form.account_name});}}><option value="">Tanpa profile</option>{brands.map(b=><option key={b.id} value={b.id}>{b.brand_name}</option>)}</select></label>
<div style={{display:'grid',gridTemplateColumns:'1fr 1fr',gap:10}}><label>Frekuensi<select className="form-select" value={form.frequency} onChange={e=>setForm({...form,frequency:e.target.value})}><option value="daily">Harian</option><option value="weekly">Mingguan</option><option value="monthly">Bulanan</option></select></label><label>Zona waktu<input className="form-input" value={form.timezone} onChange={e=>setForm({...form,timezone:e.target.value})}/></label></div>
<div style={{display:'grid',gridTemplateColumns:'1fr 1fr 1fr',gap:10}}>{form.frequency==='weekly'&&<label>Hari<select className="form-select" value={form.weekday} onChange={e=>setForm({...form,weekday:e.target.value})}>{['Minggu','Senin','Selasa','Rabu','Kamis','Jumat','Sabtu'].map((x,i)=><option key={x} value={i}>{x}</option>)}</select></label>}{form.frequency==='monthly'&&<label>Tanggal<input className="form-input" type="number" min="1" max="28" value={form.day_of_month} onChange={e=>setForm({...form,day_of_month:e.target.value})}/></label>}<label>Jam<input className="form-input" type="number" min="0" max="23" value={form.hour} onChange={e=>setForm({...form,hour:e.target.value})}/></label><label>Menit<input className="form-input" type="number" min="0" max="59" value={form.minute} onChange={e=>setForm({...form,minute:e.target.value})}/></label></div>
<label>Pilar (satu per baris)<textarea className="form-input" rows={8} value={form.pillars} onChange={e=>setForm({...form,pillars:e.target.value})}/></label><div style={{padding:10,border:'1px solid #334155',borderRadius:8,fontSize:12}}>Preset: <b>nutribake_editorial_v1</b><br/>Approval: storyboard · Social posting: off</div><button disabled={busy} className="btn btn-primary">Simpan Schedule (Paused)</button>{message&&<div>{message}</div>}</form>
<section style={{display:'grid',gap:18,alignContent:'start'}}>{data.notifications?.some(n=>!n.read_at)&&<div className="card" style={{padding:14,border:'1px solid #f59e0b'}}>🔔 <b>{data.notifications.filter(n=>!n.read_at).length} storyboard menunggu perhatian</b></div>}<div className="card" style={{padding:20}}><h3>Schedules</h3>{data.schedules.length===0?<p>Belum ada schedule.</p>:data.schedules.map(s=><div key={s.id} style={{padding:'12px 0',borderBottom:'1px solid var(--border-color)',display:'flex',justifyContent:'space-between',gap:10}}><div><b>{s.name}</b><div style={{fontSize:12,color:'var(--text-muted)'}}>{s.frequency} · {s.timezone} · next {s.next_run_at?new Date(s.next_run_at).toLocaleString('id-ID'):'-'}</div><span style={{fontSize:12}}>{s.status}</span></div><div style={{display:'flex',gap:6}}><button disabled={busy} className="btn" onClick={()=>action(s.id,'run')}>Run Now</button><button disabled={busy} className="btn" onClick={()=>action(s.id,'toggle',s.status==='active'?'paused':'active')}>{s.status==='active'?'Pause':'Aktifkan'}</button></div></div>)}</div>
<div className="card" style={{padding:20}}><h3>Run History</h3>{data.runs.slice(0,15).map(r=>{const result=typeof r.operator_result_json==='string'?JSON.parse(r.operator_result_json):r.operator_result_json;return <div key={r.id} style={{padding:'9px 0',borderBottom:'1px solid var(--border-color)'}}><b>{r.schedule_name}</b> · {r.status}<div style={{fontSize:12,color:'var(--text-muted)'}}>{r.id} {r.operator_job_id&&`· ${r.operator_job_id}`} · attempt {r.attempt_count}</div>{r.status==='awaiting_approval'&&<a href={result?.campaign_id?`/pillar-campaigns/${result.campaign_id}`:'/pillar-campaigns'}>Buka campaign untuk review →</a>}{r.status==='failed'&&<button disabled={busy} className="btn" onClick={()=>retry(r.id)}>Retry</button>}</div>})}</div></section></div></main>}
