import { NextResponse } from 'next/server';
import { requireTenantAdmin } from '@/lib/auth';
import { encryptSecret } from '@/lib/encrypted-secret';
import { getNotificationPreference,saveNotificationPreference } from '@/lib/notification-outbox-repository';

const EVENTS=['awaiting_approval','failed','auto_paused','missed_run','completed'];
const validTime=value=>value===null||value===''||/^([01]\d|2[0-3]):[0-5]\d$/.test(value);
function validTimezone(value){try{new Intl.DateTimeFormat('id-ID',{timeZone:value}).format();return true;}catch{return false;}}
function publicPreference(row){return {enabled:Boolean(row?.enabled),channel:'telegram',chat_id:row?.chat_id||'',configured:Boolean(row?.bot_token_ciphertext),events:Array.isArray(row?.events_json)?row.events_json:(typeof row?.events_json==='string'?JSON.parse(row.events_json):['awaiting_approval','failed','auto_paused','missed_run']),quiet_start:row?.quiet_start||'',quiet_end:row?.quiet_end||'',timezone:row?.timezone||'Asia/Jakarta'};}

export async function GET(request){try{requireTenantAdmin(request);return NextResponse.json({success:true,settings:publicPreference(await getNotificationPreference())});}catch(e){return NextResponse.json({success:false,error:e.message},{status:e.status||500});}}
export async function PUT(request){try{const user=requireTenantAdmin(request),body=await request.json(),current=await getNotificationPreference();const events=[...new Set(Array.isArray(body.events)?body.events:[])];if(!events.length||events.some(x=>!EVENTS.includes(x)))return NextResponse.json({success:false,error:'Pilih minimal satu event notifikasi yang valid.'},{status:400});if(!validTime(body.quiet_start)||!validTime(body.quiet_end))return NextResponse.json({success:false,error:'Quiet hours harus berformat HH:mm.'},{status:400});if(!validTimezone(body.timezone||'Asia/Jakarta'))return NextResponse.json({success:false,error:'Zona waktu tidak valid.'},{status:400});if(body.enabled&&(!String(body.chat_id||'').trim()||(!current?.bot_token_ciphertext&&!String(body.bot_token||'').trim())))return NextResponse.json({success:false,error:'Chat ID dan bot token wajib diisi saat notifikasi diaktifkan.'},{status:400});const token=String(body.bot_token||'').trim();if(token&&!/^\d+:[A-Za-z0-9_-]+$/.test(token))return NextResponse.json({success:false,error:'Format Telegram bot token tidak valid.'},{status:400});const saved=await saveNotificationPreference({enabled:Boolean(body.enabled),chat_id:String(body.chat_id||'').trim(),bot_token_ciphertext:token?encryptSecret(token):current?.bot_token_ciphertext,events,quiet_start:body.quiet_start||null,quiet_end:body.quiet_end||null,timezone:body.timezone||'Asia/Jakarta'},user.id);return NextResponse.json({success:true,settings:publicPreference(saved)});}catch(e){return NextResponse.json({success:false,error:e.message},{status:e.status||500});}}
