import { NextResponse } from 'next/server';
import { getCurrentUser } from '@/lib/auth';
import { listOperatorPresets, isSystemOperatorPreset, getCustomOperatorPresets, hydrateOperatorPresetCache, normalizePresetCampaignKinds } from '@/lib/operator-presets';
import { getSetting, setSetting } from '@/lib/db';

export const dynamic='force-dynamic';
function requireAdmin(request){const user=getCurrentUser(request);if(!user||user.role!=='admin'){const e=new Error('Hanya Admin tenant yang dapat mengelola preset.');e.status=403;throw e;}return user;}
function requireUser(request){const user=getCurrentUser(request);if(!user){const e=new Error('Unauthorized');e.status=401;throw e;}return user;}
function normalize(body,current={}){const key=String(body.key||'').trim().toLowerCase();if(!/^[a-z0-9][a-z0-9_-]{2,63}$/.test(key)){const e=new Error('Key preset tidak valid.');e.status=400;throw e;}if(isSystemOperatorPreset(key)){const e=new Error('Preset sistem tidak dapat ditimpa. Clone dengan key baru.');e.status=409;throw e;}const config=body.config;if(!config||typeof config!=='object'||Array.isArray(config)){const e=new Error('Config preset wajib berupa object JSON.');e.status=400;throw e;}return {...config,campaign_kinds:normalizePresetCampaignKinds(config.campaign_kinds),schema_version:'2',label:String(body.label||config.label||key).trim(),revision:Number(current.revision||0)+1};}
export async function GET(request){try{const user=requireUser(request);hydrateOperatorPresetCache(user.tenantId,getSetting('operator_presets_json')||'{}');return NextResponse.json({success:true,presets:listOperatorPresets()});}catch(e){return NextResponse.json({success:false,error:e.message},{status:e.status||500});}}
export async function POST(request){try{const user=requireAdmin(request);hydrateOperatorPresetCache(user.tenantId,getSetting('operator_presets_json')||'{}');const body=await request.json(),all=getCustomOperatorPresets();if(all[body.key])return NextResponse.json({success:false,error:'Key preset sudah ada.'},{status:409});const config=normalize(body);all[body.key]=config;await setSetting('operator_presets_json',JSON.stringify(all));hydrateOperatorPresetCache(user.tenantId,all);return NextResponse.json({success:true,key:body.key,preset:config},{status:201});}catch(e){return NextResponse.json({success:false,error:e.message},{status:e.status||500});}}
